apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pne7
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-pne7@sha256:4c727bf9b9d914f2d63e3f07398aecae5e6ec2657228262d98f9644f5e96071b
        name: my-nodejs
        resources: {}
status: {}
